language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-amg' ]; then cd .. && eval "mv $currentfolder generator-amg" && cd generator-amg; fi

